"""initial schema

Revision ID: 4ddaaf0149d5
Revises: 
Create Date: 2026-04-30 22:08:45.245374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddaaf0149d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('has_digital', sa.Integer(), nullable=True),
    sa.Column('has_physical', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'paid', 'fulfilled', 'shipped', 'cancelled')", name='ck_order_status_enum'),
    sa.CheckConstraint('total_amount >= 0', name='ck_order_total_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_orders_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_stripe_session_id'), ['stripe_session_id'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('map_code', sa.String(), nullable=True),
    sa.Column('scale', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('region_tag', sa.String(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_label', sa.String(), nullable=True),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('updated_year', sa.String(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type IN ('digital_map', 'physical_book', 'donation', 'bundle')", name='ck_product_type_enum'),
    sa.CheckConstraint('price >= 0', name='ck_product_price_nonneg'),
    sa.CheckConstraint('stock_quantity IS NULL OR stock_quantity >= 0', name='ck_product_stock_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_active', ['active'], unique=False)
        batch_op.create_index('ix_products_map_code', ['map_code'], unique=False)
        batch_op.create_index('ix_products_type', ['type'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.CheckConstraint('price_at_purchase >= 0', name='ck_orderitem_price_nonneg'),
    sa.CheckConstraint('quantity > 0', name='ck_orderitem_qty_pos'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_type')
        batch_op.drop_index('ix_products_map_code')
        batch_op.drop_index('ix_products_active')

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_stripe_session_id'))
        batch_op.drop_index('ix_orders_status')
        batch_op.drop_index('ix_orders_created_at')

    op.drop_table('orders')
    # ### end Alembic commands ###
